### ISSUE TITLE
Missing source file.

### ISSUE THREAD

**Issue by marr75** [Mhburg/AwsomeInventory#22]
`Source file 'E:\Development\repos\AwsomeInventory\src\V1.1\Common\Plugins\CustomRace.cs' could not be found.`

Looks like you forgot to add it in your latest round of commits.

**Comment by marr75** [comment]
By the way, this project is fantastic.

**Comment by Mhburg** [comment]
Thank you for your kind word.
Missing files are added in the latest commit
