### ISSUE TITLE
Could not reserve Thing error.

### ISSUE THREAD

**Issue by PerfectlyInSane** [Mhburg/AwsomeInventory#33]
I'm getting this error whenever multiple pawns try to access the same meal stack.

Could not reserve Thing_MealFine2590905(current stack count: 45) (layer: null) for Mosquito for job TakeInventory (Job_6474751) A=Thing_MealFine2590905 (now doing job TakeInventory (Job_6474751) A=Thing_MealFine2590905(curToil=-1)) for maxPawns 1 and stackCount -1. Existing reserver: Abanqueiro doing job Ingest (Job_6474407) A=Thing_MealFine2590905 (toilIndex=4)
Verse.Log:Error(String, Boolean)
Verse.AI.ReservationManager:DMD<DMD<LogCouldNotReserveError_Patch1>?1345403392::LogCouldNotReserveError_Patch1>(ReservationManager, Pawn, Job, LocalTargetInfo, Int32, Int32, ReservationLayerDef)
Verse.AI.ReservationManager:DMD<DMD<Reserve_Patch3>?-838518144::Reserve_Patch3>(ReservationManager, Pawn, Job, LocalTargetInfo, Int32, Int32, ReservationLayerDef, Boolean)
Verse.AI.ReservationUtility:Reserve(Pawn, LocalTargetInfo, Job, Int32, Int32, ReservationLayerDef, Boolean)
Verse.AI.JobDriver_TakeInventory:TryMakePreToilReservations(Boolean)
Verse.AI.Pawn_JobTracker:DMD<DMD<StartJob_Patch2>?989432448::StartJob_Patch2>(Pawn_JobTracker, Job, JobCondition, ThinkNode, Boolean, Boolean, ThinkTreeDef, Nullable`1, Boolean, Boolean)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:DMD<DMD<EndCurrentJob_Patch1>?1173726336::EndCurrentJob_Patch1>(Pawn_JobTracker, JobCondition, Boolean, Boolean)
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Tick()
Verse.TickList:DMD<DMD<Tick_Patch2>?1858760064::Tick_Patch2>(TickList)
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()

Results in pawns standing still till they can get to the stack of meals to grab one. I am using "Stack XXL" to increase the stack size, the meals are in a Wall fridge from "Rim Fridge".

**Comment by Mhburg** [comment]
The exception is due to the job for the pawn who was about to take inventory was suspended. The suspended job was put in queue, and when the pawn gets around to do the job, the meal was already taken. The job to take inventory is changed in the latest commit 47d53c0dc7f05da9d236a020eba97aabe2429229, so it cannot be suspended.

**Comment by PerfectlyInSane** [comment]
Appreciate you looking into and fixing this bug. Cheers mate.

**Comment by Mhburg** [comment]
Thank you for reporting. Have a good day.
