### ISSUE TITLE
[Feat] Allow adding weapons to loadout from the right-click floating menu

### ISSUE THREAD

**Issue by MadaraUchiha** [Mhburg/AwsomeInventory#39]
Feature Request: Awesome Inventory to allow adding weapons to the loadout directly from the right click menu.

Optional: If CE is loaded, offer to add N magazines of ammo at the same time.

**Comment by Mhburg** [comment]
You can now add weapons/apparels to loadout either right-click in gear tab or the first time you pick it up with AI's equip option. However, AI's equip option is disabled if you have Simple Sidearm loaded. I may change add support for that.
