### ISSUE TITLE
[Bug] Adding ammo to loadout leads to colonist hoarding hundreds of ammo even though less is requested

### ISSUE THREAD

**Issue by MadaraUchiha** [Mhburg/AwsomeInventory#40]
Probably because I also use OgreStack and it's one stack of ammo.

![image](https://user-images.githubusercontent.com/1188951/81230318-ef248c80-8ff9-11ea-8587-7dcd616fa1fd.png)

**Comment by Mhburg** [comment]
![image](https://user-images.githubusercontent.com/14916037/81278808-2dcf3c80-9024-11ea-8602-e314da040b7d.png)

**Comment by Mhburg** [comment]
There is a job returned by JobGiver_TakeAndEquip in CE, which restock ammo and there is a chance that it fills up the inventory. However, it still doesn't entirely explain your case.

**Comment by MadaraUchiha** [comment]
As a sidenote, you should use `JobMaker.MakeJob()` instead of `new Job()` :)

But yes, you're trying to take as much as the pawn can fit in inventory (how does that work? By weight? By bulk?), rather than `Mathf.Max(numToCarry, numRequested)`.

**Comment by Mhburg** [comment]
The screenshot is from CE's code, not mine

**Comment by Mhburg** [comment]
Fixed
