### ISSUE TITLE
Unable to acquire Unity-debugging-2019.x.zip

### ISSUE THREAD

**Issue by BUTTERSKY11** [Mhburg/AwsomeInventory#45]
As of now, the wiki tutorial does not work. dnSpy has seemed to remove all releases and I cannot even find the files for Unity-debugging in the actions tab or I missed it, I am unable to continue with an attempt to work with Rimworld.

**Comment by Mhburg** [comment]
dnSpy did seem to remove the downloads of their softwares, but if you click the links provided in the tutorial, you can still download the debug files.
